### PR TITLE
Exception when creating xci files in mutipack mode with latest games.

### PR DESCRIPTION
**Pull request by retrodanuart**
Hi, when generating xci files merging base, updated and dlc files with newest games like Steel Assault or Asterix Slap them all, the program throws an exception and only includes the base file:

        * Appending: 99b8449d593fec4063eac8f31a944f61.nca
        * Appending: d2a4bc145cec64472b99cd619fd97e5a.nca
        * Appending: 5c4b1dc5545ef6146bf56e1e211dd54d.nca
        * Appending: ebfa02480a4baa692ddd939ddcdb73f7.cnmt.nca
100%|█████████████████████████████████████?| 1.38G/1.38G [00:12<00:00, 114MB/s]E
xception: list index out of range

### CODE REVIEW

**Comment by Masamune3210** [comment]
Make sure your files are valid, ive had that error when corruption was present or the files were otherwise in an unexpected state. If they are valid try rebuilding them to see if that helps

**Comment by retrodanuart** [comment]
Yes I think the files could be corrupted, since the size at nintendo.com game info is different. Thanks for the reply.

**Comment by retrodanuart** [comment]
Having this problem with new games an updates again. Really don't think is a problem of corrupted files. Maybe something has changed in new games.

**Comment by StHiryu** [comment]
Tried again with latest keys and everything works at expected. 

This issue can be closed.

**Comment by retrodanuart** [comment]
Tried again with latest keys and everything works at expected. 

This issue can be closed.

**Pull request closed without merging**
